-- ---------------------------------------------------------------------------
-- Distribución de tiendas
--
-- De quién es cada comercio: Grupo A de Esteban, Grupo B de Candelaria. El
-- tablero pinta cada tienda con el color de su dueño en todas las pantallas
-- —azul Esteban, rosa Candelaria— y la lista se edita desde /tiendas.
--
-- En `mensual` y `cancelados` la tienda es solo un texto, sin id, así que el
-- dueño se encuentra por nombre. `clave` es ese nombre sin acentos, sin
-- mayúsculas y sin nada que no sea letra o número (`claveTienda()` en
-- `src/lib/responsables.ts`), y `alias` junta las otras formas en que el
-- mismo comercio aparece escrito: «Mayor Bag» en mensual, «dropOFF MayorBag»
-- en colectas.
--
-- Correr una vez en el SQL Editor de Supabase. Es aditiva e idempotente: la
-- carga inicial usa `on conflict do nothing`, así que volver a correrla no
-- pisa lo que se haya editado desde la web.
--
-- Carga inicial: 364 tiendas, 181 de Esteban y 183 de Candelaria.
--
-- Para volver atrás: `drop table public.tiendas_responsables;`.
-- ---------------------------------------------------------------------------

begin;

create table if not exists public.tiendas_responsables (
  id           uuid primary key default gen_random_uuid(),
  nombre       text not null,

  -- Única: un comercio no puede tener dos dueños. Los alias no entran en el
  -- índice porque viven en un arreglo; que no se repitan lo revisa la web
  -- antes de guardar.
  clave        text not null unique,
  alias        text[] not null default '{}',

  -- Correo del perfil, el mismo identificador que `editado_por`.
  responsable  text not null
               check (responsable in ('esteban@rapiboy.com', 'candelaria@rapiboy.com')),

  -- La sección de la lista original: con colecta, sin colecta o recién sumada.
  seccion      text not null default 'NUEVA'
               check (seccion in ('COLECTA', 'NO_COLECTA', 'NUEVA')),

  creado_en    timestamptz not null default now(),
  creado_por   text,
  editado_en   timestamptz,
  editado_por  text
);

create index if not exists tiendas_responsables_responsable_idx
  on public.tiendas_responsables (responsable);

-- Igual que el resto: RLS prendido y sin políticas. Solo el servidor la lee.
alter table public.tiendas_responsables enable row level security;

insert into public.tiendas_responsables (nombre, clave, alias, responsable, seccion)
values
  ('DropOff TERESITA EXPRESS', 'dropoffteresitaexpress', array['dropOFF TERESITA EXPRESS'], 'esteban@rapiboy.com', 'COLECTA'),
  ('DropOff Powerbatt (PowerBatt)', 'dropoffpowerbattpowerbatt', array['Powerbatt', 'dropOFF PowerBatt'], 'candelaria@rapiboy.com', 'COLECTA'),
  ('dropOFF MiMoto (Mi Moto)', 'dropoffmimotomimoto', array['Mi moto', 'dropOFF MiMoto'], 'esteban@rapiboy.com', 'COLECTA'),
  ('DropOff MayorBag (MayorBag)', 'dropoffmayorbagmayorbag', array['Mayor Bag', 'dropOFF MayorBag'], 'candelaria@rapiboy.com', 'COLECTA'),
  ('DropOff Boogie Pets (Boogie Pets)', 'dropoffboogiepetsboogiepets', array['BOOGIEPETSLANDIA', 'dropOFF BoogiePets'], 'esteban@rapiboy.com', 'COLECTA'),
  ('dropOFF Bache Critico (Bache Crítico)', 'dropoffbachecriticobachecritico', array['Bache Critico', 'dropOFF Bache Critico'], 'candelaria@rapiboy.com', 'COLECTA'),
  ('CARDIC AUTOMOTRIZ', 'cardicautomotriz', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('MULTICOMERCIALIZADORA DE HERRAMIENTAS SA DE CV', 'multicomercializadoradeherramientassadecv', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('SPG Online', 'spgonline', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('REFACCIONARIA KROCK', 'refaccionariakrock', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Grupo Fuentes Automotriz', 'grupofuentesautomotriz', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('MLDonline', 'mldonline', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Fanc Croqueterias', 'fanccroqueterias', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Mistermascotas 2', 'mistermascotas2', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Amikoo Peek', 'amikoopeek', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('AniMALL', 'animall', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('SATUS', 'satus', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Marlovet', 'marlovet', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Productos Naturales Big Life', 'productosnaturalesbiglife', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('ENVASES XENA', 'envasesxena', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('HALOMEDIC', 'halomedic', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Farmacia America', 'farmaciaamerica', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Kuangeye', 'kuangeye', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Karzov', 'karzov', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('eToledo', 'etoledo', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('STEELPRO', 'steelpro', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('DISTRIBUIDORA CORSICANA - Catering for dogs and cats', 'distribuidoracorsicanacateringfordogsandcats', array['DISTRIBUIDORA CORSICANA'], 'esteban@rapiboy.com', 'COLECTA'),
  ('WEIDEWORDL', 'weidewordl', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Innobeat', 'innobeat', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('INSUMOS FANNY', 'insumosfanny', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Comercializadora Valsan', 'comercializadoravalsan', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Comercializadora y distribuidora bat yam sa de cv', 'comercializadoraydistribuidorabatyamsadecv', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Runsa Autopartes', 'runsaautopartes', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('stovmex', 'stovmex', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Grupo Basari', 'grupobasari', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Lincky', 'lincky', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('VITAZONE MEXICO', 'vitazonemexico', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Volk''s Coruña', 'volkscoruna', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Librerias Gandhi', 'libreriasgandhi', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Librenta México', 'librentamexico', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Farmaenvios', 'farmaenvios', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('MANUALIDADES DIANA KAREN', 'manualidadesdianakaren', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Mascotas y Accesorios Mx', 'mascotasyaccesoriosmx', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('JERRY TRUCK AND AUTO ACCESORIOS', 'jerrytruckandautoaccesorios', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('TREL', 'trel', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('EASY-SHOP INTERNACIONAL', 'easyshopinternacional', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('REFACCIONES ORIGINALES JGV', 'refaccionesoriginalesjgv', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('homer design mexico', 'homerdesignmexico', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('EasyWare', 'easyware', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Gotcha Store Mx.', 'gotchastoremx', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Motorepuestos Originales', 'motorepuestosoriginales', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Grupo Aruba Internacional', 'grupoarubainternacional', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('DISTRIBUIDORAMILITAR', 'distribuidoramilitar', '{}'::text[], 'esteban@rapiboy.com', 'COLECTA'),
  ('Distribu', 'distribu', '{}'::text[], 'candelaria@rapiboy.com', 'COLECTA'),
  ('Altra Pisos', 'altrapisos', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('1HOME', '1home', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Dasam', 'dasam', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Distribuidora Aoo', 'distribuidoraaoo', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Franz Lorenz', 'franzlorenz', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Grupo Derzu', 'grupoderzu', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Gifting', 'gifting', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Intercarnes', 'intercarnes', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Kemme Importaciones', 'kemmeimportaciones', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('REFA123.MX', 'refa123mx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('LAVE SHOP', 'laveshop', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('ricardo peñaloza', 'ricardopenaloza', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('LEVERING INSUMOS', 'leveringinsumos', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Alaciados y reconstrucción capilar', 'alaciadosyreconstruccioncapilar', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Libantique -libros antiguos-', 'libantiquelibrosantiguos', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Azume Baños y Cocinas', 'azumebanosycocinas', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('MUCHA FIESTA', 'muchafiesta', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('BIZNES PHARMA', 'biznespharma', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('REFACCIONARIA KEVAAL', 'refaccionariakevaal', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('CARICIA AROMATICA', 'cariciaaromatica', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Repuestos Automotrices Carivan S.A. de C.V.', 'repuestosautomotricescarivansadecv', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Central de Autopartes', 'centraldeautopartes', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Ballistik', 'ballistik', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('COLLECTION2020', 'collection2020', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Bin Boutique', 'binboutique', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Comercializadora Commplaza', 'comercializadoracommplaza', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('CHEVROLET SOL VALLE DORADO', 'chevroletsolvalledorado', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('COMERCIALIZADORA DAPASE', 'comercializadoradapase', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('cmpimex', 'cmpimex', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DISTRIBUCIONES MONTES DE OCA', 'distribucionesmontesdeoca', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('DISTRITO VET', 'distritovet', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DISTRIBUIDORA DE HUMIDORES DE OCCIDENTE', 'distribuidoradehumidoresdeoccidente', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Elefantito', 'elefantito', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DQ Shop', 'dqshop', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('FARMACIA ECONOPET', 'farmaciaeconopet', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DRIVEDEPOTMX', 'drivedepotmx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('GAROD EPP', 'garodepp', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DULCE FIESTA', 'dulcefiesta', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Home & Business +', 'homebusiness', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('EARS AND PAWS', 'earsandpaws', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Modas NT', 'modasnt', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Grupo Cellcom', 'grupocellcom', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Nihome', 'nihome', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Hilda Sam', 'hildasam', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Omoyal Organica', 'omoyalorganica', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('ikusy', 'ikusy', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Plc suministros', 'plcsuministros', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Imasi hernandez Rodiguez', 'imasihernandezrodiguez', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('REGALOS INCREIBLES', 'regalosincreibles', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('INDUSTRIAS PORTALES SA DE CV', 'industriasportalessadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Select Sound', 'selectsound', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Jaén Comercializadora', 'jaencomercializadora', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Serpentinas shop', 'serpentinasshop', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Librería Renart', 'libreriarenart', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Tiendas Key', 'tiendaskey', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('MAYOREO LITELINE', 'mayoreoliteline', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Zoe Shopping', 'zoeshopping', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('MEDICA STORE', 'medicastore', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('All in one shop', 'allinoneshop', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Mercasync', 'mercasync', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('BAZAR-ZUKI', 'bazarzuki', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('MODAVELA', 'modavela', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('BLACKGATE', 'blackgate', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('MULTIPRODUCTOS Y EXPENDABLES', 'multiproductosyexpendables', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Blokke Collectibles', 'blokkecollectibles', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Nemi Pet Shop', 'nemipetshop', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Canvas Yamkay', 'canvasyamkay', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('PERMEDED INSUMOS DE IMPRESION', 'permededinsumosdeimpresion', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Capital Movil', 'capitalmovil', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('REDBOX CAJAROJA', 'redboxcajaroja', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Casa Baberos', 'casababeros', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Refaccionaria Mario', 'refaccionariamario', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('CLUB CITY COMPANY MEXICO', 'clubcitycompanymexico', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('REFACCIONES ESPECIALIZADAS', 'refaccionesespecializadas', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('compumexico', 'compumexico', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('TGB Superfoods', 'tgbsuperfoods', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('CREMBO', 'crembo', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Wild', 'wild', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('DHOMART NETWORK', 'dhomartnetwork', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Commercial store by Balagardos', 'commercialstorebybalagardos', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('DILE STORE', 'dilestore', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Cooperativa Lesor Diveera', 'cooperativalesordiveera', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('EL NUEVO MILENIO DE LOS NIÑOS', 'elnuevomileniodelosninos', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DaraBaby', 'darababy', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Eternium Rudeboy', 'eterniumrudeboy', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Derm Center', 'dermcenter', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('FABRICAS JUMA', 'fabricasjuma', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Emilio´s Virtual Shop', 'emiliosvirtualshop', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('FARMACIA LOS REMEDIOS', 'farmacialosremedios', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Ford Reslay', 'fordreslay', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Garufa Jeans', 'garufajeans', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Gafer', 'gafer', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Group Sapien', 'groupsapien', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Jose Fernando Galindo Robles', 'josefernandogalindorobles', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('IG COMICS', 'igcomics', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Jugueteria los Sueños Magicos', 'jugueterialossuenosmagicos', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Los Enanos', 'losenanos', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('KYA Medical', 'kyamedical', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('La Fontana Zapaterias S.A. de C.V.', 'lafontanazapateriassadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('MOLDEMANIA', 'moldemania', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Macross Pharma SA de CV', 'macrosspharmasadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('NATALIA BEATRIZ PEREZ PEREZ', 'nataliabeatrizperezperez', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('marisol martinez guzman', 'marisolmartinezguzman', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Polo Retro Of Yatch London', 'poloretroofyatchlondon', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('MÁS MOLDES MX', 'masmoldesmx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Qualite Gastronomique S de RL de CV', 'qualitegastronomiquesderldecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Rubi bisuteria y accesorios', 'rubibisuteriayaccesorios', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('RAMTEC', 'ramtec', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Yabs Mayoreo', 'yabsmayoreo', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('SUPER VARA', 'supervara', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Zapaterias Leon del Centro', 'zapateriasleondelcentro', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Surtidora Doméstica', 'surtidoradomestica', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('ORIENTAL E y D', 'orientaleyd', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('THE TOY EMPIRE', 'thetoyempire', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Inmeditex', 'inmeditex', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('VENATUS', 'venatus', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('ORYPS', 'oryps', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Ventas Libres', 'ventaslibres', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Roustore', 'roustore', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Wed Maiz', 'wedmaiz', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('FARMACLICK', 'farmaclick', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Medicom', 'medicom', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Uptown Market', 'uptownmarket', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Comercializar Zrk', 'comercializarzrk', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('CX RACING', 'cxracing', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DANIELIT', 'danielit', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Mr Fiesta', 'mrfiesta', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Comercializadora Maiz', 'comercializadoramaiz', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Fersari - FERSERAN', 'fersariferseran', array['Fersari'], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('STOCKUPCREATIVOS', 'stockupcreativos', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('FARMACIAS APFA', 'farmaciasapfa', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('VILDEPLAST, SA DE CV', 'vildeplastsadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('perraco skateshop', 'perracoskateshop', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('EL BISTURI', 'elbisturi', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Artefacto club', 'artefactoclub', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('SUMINISTROS TECNOLOGICOS ON DEMAND', 'suministrostecnologicosondemand', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Grupo GVDF', 'grupogvdf', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Tendencias CDMX', 'tendenciascdmx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Detallitos Jumena', 'detallitosjumena', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Baby Vainilla', 'babyvainilla', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Likeshop1', 'likeshop1', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Desarrolladora NSCCT', 'desarrolladoranscct', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('ITZAMARAYLPEZ', 'itzamaraylpez', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('BAZACOM', 'bazacom', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Distribuidora CDB', 'distribuidoracdb', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Audioland Electronics', 'audiolandelectronics', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('LA PULGA', 'lapulga', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('MEXICO ORIGINAL AMANTOLI', 'mexicooriginalamantoli', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('GALENO MX', 'galenomx', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('ECOENFOQUES GRMX', 'ecoenfoquesgrmx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Amazon', 'amazon', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Envases EMK SAS DE CV', 'envasesemksasdecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Automotriz grupo e', 'automotrizgrupoe', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('GRIMEX', 'grimex', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('MAXCELL TLALNEPANTLA', 'maxcelltlalnepantla', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('topsking sa de cv', 'topskingsadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Distribuidora Salguero SA de CV', 'distribuidorasalguerosadecv', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('DISTPV', 'distpv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('PYRASPORT', 'pyrasport', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('CCYDI CDMX', 'ccydicdmx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('PINEDA JEANS', 'pinedajeans', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Importadora Toro de Metal', 'importadoratorodemetal', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('MDJ', 'mdj', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('We love Luana', 'weloveluana', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Distribución Aromatica', 'distribucionaromatica', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('GRUPO JOHN VANNA', 'grupojohnvanna', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Multi Shop 29', 'multishop29', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Envíame CDMX', 'enviamecdmx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Vitality Shop - Estrella shop', 'vitalityshopestrellashop', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Old School Sports SA de CV', 'oldschoolsportssadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Accesorios Really', 'accesoriosreally', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('libreria.correa.mx', 'libreriacorreamx', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Vitality Shop 29', 'vitalityshop29', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('COMERCIALIZADORA DE INTERCAMBIO MARIANA SA DE CV', 'comercializadoradeintercambiomarianasadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('En cuadro', 'encuadro', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Promising', 'promising', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Nutrición para el Bienestar de Mascotas MX', 'nutricionparaelbienestardemascotasmx', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Imagina Decoart', 'imaginadecoart', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('DISTRIBUIDORA MERAZ', 'distribuidorameraz', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Destiny 911', 'destiny911', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('AUVEN', 'auven', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Fundas premium', 'fundaspremium', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('IOENTERPRISES - Delta Foods Rapiboy MX', 'ioenterprisesdeltafoodsrapiboymx', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Move Up', 'moveup', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Distribuidora Mundo Animal', 'distribuidoramundoanimal', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('LAIKA', 'laika', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Sales Online', 'salesonline', '{}'::text[], 'esteban@rapiboy.com', 'NO_COLECTA'),
  ('Cool and enjoy', 'coolandenjoy', '{}'::text[], 'candelaria@rapiboy.com', 'NO_COLECTA'),
  ('Masterwash Bluemango', 'masterwashbluemango', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('TAYGA SPORTS', 'taygasports', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('BENJAMIN ULISES MARTINEZ ALCANTARA', 'benjaminulisesmartinezalcantara', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Ultraliss', 'ultraliss', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Orgánico & Natural', 'organiconatural', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('KYA BOUTIQUE', 'kyaboutique', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Cake Sex Shop', 'cakesexshop', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Natura Stevia', 'naturastevia', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Have Fun Times', 'havefuntimes', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Stickers Mototors', 'stickersmototors', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('RODISAME - Rapiboy MX', 'rodisamerapiboymx', array['RODISAME'], 'esteban@rapiboy.com', 'NUEVA'),
  ('Tatich', 'tatich', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('GETSMARTCA', 'getsmartca', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Joydanshop', 'joydanshop', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Distribuidora Liqm', 'distribuidoraliqm', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Box-N-Toy', 'boxntoy', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('INVERSIONES.EN.TEGNOLOGIA.CC', 'inversionesentegnologiacc', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Nutrición Clínica en Casa', 'nutricionclinicaencasa', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('ZUS CHOCOLATE', 'zuschocolate', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('CAPUAN', 'capuan', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('KI FOODS SA DE CV', 'kifoodssadecv', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('VERTICE Moto Gear - Rapiboy MX', 'verticemotogearrapiboymx', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Zito Fitness - Rapiboy México', 'zitofitnessrapiboymexico', array['Zito Fitness'], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Rosa Garcia', 'rosagarcia', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Navamatic Dropoff - Rapiboy MX', 'navamaticdropoffrapiboymx', array['Navamatic Dropoff', 'dropOFF Navamatic'], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Yupi Yaju - Rapiboy', 'yupiyajurapiboy', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('ImpresionaDECC', 'impresionadecc', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Berrckson Merch', 'berrcksonmerch', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Mav Dino', 'mavdino', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('PROBIKE', 'probike', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('La Fábrica de los Regalos', 'lafabricadelosregalos', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Concepcion', 'concepcion', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Plumas del centro', 'plumasdelcentro', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Lamparas Aranza - leody', 'lamparasaranzaleody', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('HOUSELECTRIC', 'houselectric', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('DEPORTES GALAXIA UNIVERSUM', 'deportesgalaxiauniversum', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('3d Print Lab', '3dprintlab', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Wayne Medical', 'waynemedical', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Chicos Olé', 'chicosole', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('GMMendoza', 'gmmendoza', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('KAVIAR-KAN', 'kaviarkan', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Ideas Creativas', 'ideascreativas', array['Ideas creativas in'], 'esteban@rapiboy.com', 'NUEVA'),
  ('Ambrosia', 'ambrosia', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Honda Refacciones', 'hondarefacciones', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('JOYEE', 'joyee', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Mi Bebe Genio', 'mibebegenio', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('FARMAVIDZ', 'farmavidz', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('OHplast', 'ohplast', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Natural Complement', 'naturalcomplement', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Regasa automotriz', 'regasaautomotriz', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Mega Audio', 'megaaudio', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Stylit Mexico', 'stylitmexico', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('VENCORT', 'vencort', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('QuetzaliaShopNet', 'quetzaliashopnet', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('ZULUNA', 'zuluna', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Nutripet Marcket', 'nutripetmarcket', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Somos Pura', 'somospura', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Jasha', 'jasha', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Braulio', 'braulio', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('GRYC INNOVACIONES TECNOLOGICAS', 'grycinnovacionestecnologicas', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Paws & Prind', 'pawsprind', array['Paws & Prind 3D'], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Canek Ix Mol', 'canekixmol', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Dregonix Protección', 'dregonixproteccion', array['Dregonix Protección Total'], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Veterinaria Casthell', 'veterinariacasthell', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Todoloencuentrasmex', 'todoloencuentrasmex', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Librantique', 'librantique', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Mariana Ramirez Shoes', 'marianaramirezshoes', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Distribuidora Agro-Veterinaria Casthell', 'distribuidoraagroveterinariacasthell', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Probombs', 'probombs', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Velomaravilloso', 'velomaravilloso', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('ADIRF MARKET', 'adirfmarket', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Harlan Yussef Palma Soto', 'harlanyussefpalmasoto', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Distribuidora Sayulizzy', 'distribuidorasayulizzy', array['Distribuidora Sayulizzy (Lunita)'], 'esteban@rapiboy.com', 'NUEVA'),
  ('Emily Beauty', 'emilybeauty', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Capline', 'capline', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Auto-partsvags', 'autopartsvags', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('KOLONGTECH', 'kolongtech', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('todoloencuentrasenedomex', 'todoloencuentrasenedomex', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('MDW OK CLEAN', 'mdwokclean', array['Comercializadora MDW OK CLEAN'], 'esteban@rapiboy.com', 'NUEVA'),
  ('Moon Cherry', 'mooncherry', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('La anteojeria del tio Rick', 'laanteojeriadeltiorick', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('GRADAN', 'gradan', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('CNG MEX', 'cngmex', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Brocas Triumph', 'brocastriumph', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('El quinto Bigote', 'elquintobigote', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Auto sampi parts', 'autosampiparts', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Casa gonzalez', 'casagonzalez', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Limein', 'limein', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('FUXION MEXICO', 'fuxionmexico', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('La tienda de las pantuflas', 'latiendadelaspantuflas', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('HARI TRADING', 'haritrading', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Sergio Vazquez ferrero', 'sergiovazquezferrero', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Corporativo gracia de dios', 'corporativograciadedios', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('FD FASTDRIVE', 'fdfastdrive', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Sano Mundo', 'sanomundo', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Balero Publicidad', 'baleropublicidad', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Chevrolet Unicars Vehículos', 'chevroletunicarsvehiculos', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('PiercingTown', 'piercingtown', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Cabo Racing / Cabo Toys', 'caboracingcabotoys', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('EMPACADORA THERBAL', 'empacadoratherbal', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('CORPORATIVO MIVEREL', 'corporativomiverel', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('MIS PIÑATAS MEXICANAS', 'mispinatasmexicanas', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Universo Prendido', 'universoprendido', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Javo ramirez', 'javoramirez', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Jugueteria arlequin', 'jugueteriaarlequin', array['Juguetes arlequin'], 'esteban@rapiboy.com', 'NUEVA'),
  ('Textiles Beitex', 'textilesbeitex', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Corporativo Garcia de Dios', 'corporativogarciadedios', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('EYG DISTRIBUCION Y SUMINISTROS', 'eygdistribucionysuministros', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Million Hands', 'millionhands', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Velas H101', 'velash101', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Punto Zu', 'puntozu', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Koneko', 'koneko', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('CROQUETASLAHUESOS', 'croquetaslahuesos', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('davistdaudio', 'davistdaudio', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('GMG IMPORTACIONES', 'gmgimportaciones', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Lifestyle shoes', 'lifestyleshoes', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('MOBYTOY', 'mobytoy', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('GRUPO ARCKR9', 'grupoarckr9', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Eumir Salgado', 'eumirsalgado', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('D´leo', 'dleo', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA'),
  ('Black red suplementos', 'blackredsuplementos', '{}'::text[], 'esteban@rapiboy.com', 'NUEVA'),
  ('Salud natural', 'saludnatural', '{}'::text[], 'candelaria@rapiboy.com', 'NUEVA')
on conflict (clave) do nothing;

commit;
